name: Server CI/CD

on:
  push:
    paths:
      - "server/**"
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Server Image
        run: |
          docker build -t bwkyle/lift-server:latest .
          docker push bwkyle/lift-server:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Server to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker compose pull server  # 서버 이미지만 업데이트
            docker compose up -d server  # 서버 컨테이너만 재시작
            docker image prune -f
